# Generated by Django 3.2.8 on 2022-01-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_you', models.BooleanField(default=False)),
                ('is_me', models.BooleanField(default=False)),
                ('is_her', models.BooleanField(default=False)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
