# Generated by Django 3.2.8 on 2022-01-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='User',
            new_name='user',
        ),
    ]
