# Generated by Django 3.2.8 on 2022-01-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
