# Generated by Django 3.2.8 on 2022-02-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
