# Generated by Django 3.2.9 on 2022-01-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='job_category',
        ),
    ]
