# Generated by Django 3.2.8 on 2022-02-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekapp', '0002_accesstoken'),
        ('seekapp', '0002_alter_fileupload_pdf'),
    ]

    operations = [
    ]
