# Generated by Django 3.2.9 on 2022-01-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekapp', '0002_auto_20220119_2104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
