# Generated by Django 3.2.9 on 2022-02-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekapp', '0003_auto_20220201_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='contact',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
