# Generated by Django 3.2.9 on 2022-02-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekapp', '0004_alter_jobseeker_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='contact',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
