# Generated by Django 3.2.8 on 2022-02-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekapp', '0004_auto_20220202_0851'),
        ('seekapp', '0005_alter_subscribe_contact'),
    ]

    operations = [
    ]
